apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-a
  namespace: debug-a
spec:
  selector:
    matchLabels:
      app: test-a
  template:
    metadata:
      labels:
        app: test-a
    spec:
      containers:
      - name: test-a
        image: nginx:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
      - name: other-container
        image: busybox:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        command: ["sleep", "infinity"]
